CREATE SCHEMA "content-machine";
--> statement-breakpoint
CREATE TYPE "public"."article_priority" AS ENUM('low', 'medium', 'high');--> statement-breakpoint
CREATE TYPE "public"."article_status" AS ENUM('idea', 'to_generate', 'generating', 'wait_for_publish', 'published');--> statement-breakpoint
CREATE TABLE "content-machine"."article_settings" (
	"id" serial PRIMARY KEY NOT NULL,
	"tone_of_voice" text,
	"article_structure" text,
	"max_words" integer DEFAULT 800,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content-machine"."articles" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"keywords" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"target_audience" varchar(255),
	"status" "article_status" DEFAULT 'idea' NOT NULL,
	"scheduled_at" timestamp with time zone,
	"published_at" timestamp with time zone,
	"priority" "article_priority" DEFAULT 'medium' NOT NULL,
	"estimated_read_time" integer,
	"kanban_position" integer DEFAULT 0 NOT NULL,
	"meta_description" varchar(255),
	"outline" jsonb,
	"draft" text,
	"optimized_content" text,
	"fact_check_report" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"seo_score" integer,
	"internal_links" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sources" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"generation_task_id" varchar,
	"generation_started_at" timestamp with time zone,
	"generation_completed_at" timestamp with time zone,
	"generation_error" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content-machine"."post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "content-machine"."post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content-machine"."users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"first_name" text,
	"last_name" text,
	"company_name" text,
	"domain" text,
	"product_description" text,
	"keywords" jsonb,
	"onboarding_completed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "content-machine"."post" USING btree ("name");